#!/usr/bin/env python3

import rospy
from std_msgs.msg import String, Header

def talker():
  rospy.init_node(talker)
  pub = rospy.Publisher('chatter'. Strinng, queue_size = 10)
  rate = rospt.Rate(10) # 10hz

  while not rospy.is_shutdown():
    header = Header()
    header.stamp = roospy.Time.now()

    content = "welcome to the Robotics Lab" + str(header.stamp)
    pub.publish.(content)
    rate.sleep()

  if __name__ = '__main__':
    try:
      talker()
    except rospy.ROSInterrutpException:
      pass
  
